/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SweepsRouteImport } from './routes/sweeps'
import { Route as RunsRouteImport } from './routes/runs'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as SweepsSweepIdRouteImport } from './routes/sweeps/$sweepId'
import { Route as RunsRunIdRouteImport } from './routes/runs/$runId'
import { Route as ProjectsProjectSlugRouteImport } from './routes/projects/$projectSlug'

const SweepsRoute = SweepsRouteImport.update({
  id: '/sweeps',
  path: '/sweeps',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsRoute = RunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const SweepsSweepIdRoute = SweepsSweepIdRouteImport.update({
  id: '/$sweepId',
  path: '/$sweepId',
  getParentRoute: () => SweepsRoute,
} as any)
const RunsRunIdRoute = RunsRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => RunsRoute,
} as any)
const ProjectsProjectSlugRoute = ProjectsProjectSlugRouteImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/sweeps': typeof SweepsRouteWithChildren
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sweeps/$sweepId': typeof SweepsSweepIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/runs': typeof RunsRouteWithChildren
  '/sweeps': typeof SweepsRouteWithChildren
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sweeps/$sweepId': typeof SweepsSweepIdRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/runs': typeof RunsRouteWithChildren
  '/sweeps': typeof SweepsRouteWithChildren
  '/projects/$projectSlug': typeof ProjectsProjectSlugRoute
  '/runs/$runId': typeof RunsRunIdRoute
  '/sweeps/$sweepId': typeof SweepsSweepIdRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/runs'
    | '/sweeps'
    | '/projects/$projectSlug'
    | '/runs/$runId'
    | '/sweeps/$sweepId'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/runs'
    | '/sweeps'
    | '/projects/$projectSlug'
    | '/runs/$runId'
    | '/sweeps/$sweepId'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/runs'
    | '/sweeps'
    | '/projects/$projectSlug'
    | '/runs/$runId'
    | '/sweeps/$sweepId'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RunsRoute: typeof RunsRouteWithChildren
  SweepsRoute: typeof SweepsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sweeps': {
      id: '/sweeps'
      path: '/sweeps'
      fullPath: '/sweeps'
      preLoaderRoute: typeof SweepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs': {
      id: '/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof RunsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/sweeps/$sweepId': {
      id: '/sweeps/$sweepId'
      path: '/$sweepId'
      fullPath: '/sweeps/$sweepId'
      preLoaderRoute: typeof SweepsSweepIdRouteImport
      parentRoute: typeof SweepsRoute
    }
    '/runs/$runId': {
      id: '/runs/$runId'
      path: '/$runId'
      fullPath: '/runs/$runId'
      preLoaderRoute: typeof RunsRunIdRouteImport
      parentRoute: typeof RunsRoute
    }
    '/projects/$projectSlug': {
      id: '/projects/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/projects/$projectSlug'
      preLoaderRoute: typeof ProjectsProjectSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectSlugRoute: typeof ProjectsProjectSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectSlugRoute: ProjectsProjectSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface RunsRouteChildren {
  RunsRunIdRoute: typeof RunsRunIdRoute
}

const RunsRouteChildren: RunsRouteChildren = {
  RunsRunIdRoute: RunsRunIdRoute,
}

const RunsRouteWithChildren = RunsRoute._addFileChildren(RunsRouteChildren)

interface SweepsRouteChildren {
  SweepsSweepIdRoute: typeof SweepsSweepIdRoute
}

const SweepsRouteChildren: SweepsRouteChildren = {
  SweepsSweepIdRoute: SweepsSweepIdRoute,
}

const SweepsRouteWithChildren =
  SweepsRoute._addFileChildren(SweepsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RunsRoute: RunsRouteWithChildren,
  SweepsRoute: SweepsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
