/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as LoginRouteImport } from "./routes/login";
import { Route as LocalRouteImport } from "./routes/_local";
import { Route as AuthenticatedRouteImport } from "./routes/_authenticated";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LocalProjectsRouteImport } from "./routes/_local/projects";
import { Route as AuthenticatedDashboardRouteImport } from "./routes/_authenticated/dashboard";
import { Route as AuthenticatedTeamSlugRouteImport } from "./routes/_authenticated/$teamSlug";
import { Route as LocalProjectsIndexRouteImport } from "./routes/_local/projects/index";
import { Route as AuthenticatedTeamSlugIndexRouteImport } from "./routes/_authenticated/$teamSlug/index";
import { Route as LocalProjectsProjectSlugRouteImport } from "./routes/_local/projects/$projectSlug";
import { Route as AuthenticatedSettingsApiKeysRouteImport } from "./routes/_authenticated/settings/api-keys";
import { Route as AuthenticatedRunsRunIdRouteImport } from "./routes/_authenticated/runs/$runId";
import { Route as AuthenticatedTeamSlugAppSlugRouteImport } from "./routes/_authenticated/$teamSlug/$appSlug";
import { Route as AuthenticatedTeamSlugAppSlugIndexRouteImport } from "./routes/_authenticated/$teamSlug/$appSlug/index";
import { Route as AuthenticatedTeamSlugAppSlugSettingsRouteImport } from "./routes/_authenticated/$teamSlug/$appSlug/settings";

const LoginRoute = LoginRouteImport.update({
  id: "/login",
  path: "/login",
  getParentRoute: () => rootRouteImport,
} as any);
const LocalRoute = LocalRouteImport.update({
  id: "/_local",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: "/_authenticated",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const LocalProjectsRoute = LocalProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => LocalRoute,
} as any);
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: "/dashboard",
  path: "/dashboard",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTeamSlugRoute = AuthenticatedTeamSlugRouteImport.update({
  id: "/$teamSlug",
  path: "/$teamSlug",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const LocalProjectsIndexRoute = LocalProjectsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => LocalProjectsRoute,
} as any);
const AuthenticatedTeamSlugIndexRoute =
  AuthenticatedTeamSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedTeamSlugRoute,
  } as any);
const LocalProjectsProjectSlugRoute =
  LocalProjectsProjectSlugRouteImport.update({
    id: "/$projectSlug",
    path: "/$projectSlug",
    getParentRoute: () => LocalProjectsRoute,
  } as any);
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: "/settings/api-keys",
    path: "/settings/api-keys",
    getParentRoute: () => AuthenticatedRoute,
  } as any);
const AuthenticatedRunsRunIdRoute = AuthenticatedRunsRunIdRouteImport.update({
  id: "/runs/$runId",
  path: "/runs/$runId",
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTeamSlugAppSlugRoute =
  AuthenticatedTeamSlugAppSlugRouteImport.update({
    id: "/$appSlug",
    path: "/$appSlug",
    getParentRoute: () => AuthenticatedTeamSlugRoute,
  } as any);
const AuthenticatedTeamSlugAppSlugIndexRoute =
  AuthenticatedTeamSlugAppSlugIndexRouteImport.update({
    id: "/",
    path: "/",
    getParentRoute: () => AuthenticatedTeamSlugAppSlugRoute,
  } as any);
const AuthenticatedTeamSlugAppSlugSettingsRoute =
  AuthenticatedTeamSlugAppSlugSettingsRouteImport.update({
    id: "/settings",
    path: "/settings",
    getParentRoute: () => AuthenticatedTeamSlugAppSlugRoute,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/$teamSlug": typeof AuthenticatedTeamSlugRouteWithChildren;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/projects": typeof LocalProjectsRouteWithChildren;
  "/$teamSlug/$appSlug": typeof AuthenticatedTeamSlugAppSlugRouteWithChildren;
  "/runs/$runId": typeof AuthenticatedRunsRunIdRoute;
  "/settings/api-keys": typeof AuthenticatedSettingsApiKeysRoute;
  "/projects/$projectSlug": typeof LocalProjectsProjectSlugRoute;
  "/$teamSlug/": typeof AuthenticatedTeamSlugIndexRoute;
  "/projects/": typeof LocalProjectsIndexRoute;
  "/$teamSlug/$appSlug/settings": typeof AuthenticatedTeamSlugAppSlugSettingsRoute;
  "/$teamSlug/$appSlug/": typeof AuthenticatedTeamSlugAppSlugIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/login": typeof LoginRoute;
  "/dashboard": typeof AuthenticatedDashboardRoute;
  "/runs/$runId": typeof AuthenticatedRunsRunIdRoute;
  "/settings/api-keys": typeof AuthenticatedSettingsApiKeysRoute;
  "/projects/$projectSlug": typeof LocalProjectsProjectSlugRoute;
  "/$teamSlug": typeof AuthenticatedTeamSlugIndexRoute;
  "/projects": typeof LocalProjectsIndexRoute;
  "/$teamSlug/$appSlug/settings": typeof AuthenticatedTeamSlugAppSlugSettingsRoute;
  "/$teamSlug/$appSlug": typeof AuthenticatedTeamSlugAppSlugIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/_authenticated": typeof AuthenticatedRouteWithChildren;
  "/_local": typeof LocalRouteWithChildren;
  "/login": typeof LoginRoute;
  "/_authenticated/$teamSlug": typeof AuthenticatedTeamSlugRouteWithChildren;
  "/_authenticated/dashboard": typeof AuthenticatedDashboardRoute;
  "/_local/projects": typeof LocalProjectsRouteWithChildren;
  "/_authenticated/$teamSlug/$appSlug": typeof AuthenticatedTeamSlugAppSlugRouteWithChildren;
  "/_authenticated/runs/$runId": typeof AuthenticatedRunsRunIdRoute;
  "/_authenticated/settings/api-keys": typeof AuthenticatedSettingsApiKeysRoute;
  "/_local/projects/$projectSlug": typeof LocalProjectsProjectSlugRoute;
  "/_authenticated/$teamSlug/": typeof AuthenticatedTeamSlugIndexRoute;
  "/_local/projects/": typeof LocalProjectsIndexRoute;
  "/_authenticated/$teamSlug/$appSlug/settings": typeof AuthenticatedTeamSlugAppSlugSettingsRoute;
  "/_authenticated/$teamSlug/$appSlug/": typeof AuthenticatedTeamSlugAppSlugIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/login"
    | "/$teamSlug"
    | "/dashboard"
    | "/projects"
    | "/$teamSlug/$appSlug"
    | "/runs/$runId"
    | "/settings/api-keys"
    | "/projects/$projectSlug"
    | "/$teamSlug/"
    | "/projects/"
    | "/$teamSlug/$appSlug/settings"
    | "/$teamSlug/$appSlug/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/login"
    | "/dashboard"
    | "/runs/$runId"
    | "/settings/api-keys"
    | "/projects/$projectSlug"
    | "/$teamSlug"
    | "/projects"
    | "/$teamSlug/$appSlug/settings"
    | "/$teamSlug/$appSlug";
  id:
    | "__root__"
    | "/"
    | "/_authenticated"
    | "/_local"
    | "/login"
    | "/_authenticated/$teamSlug"
    | "/_authenticated/dashboard"
    | "/_local/projects"
    | "/_authenticated/$teamSlug/$appSlug"
    | "/_authenticated/runs/$runId"
    | "/_authenticated/settings/api-keys"
    | "/_local/projects/$projectSlug"
    | "/_authenticated/$teamSlug/"
    | "/_local/projects/"
    | "/_authenticated/$teamSlug/$appSlug/settings"
    | "/_authenticated/$teamSlug/$appSlug/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  LocalRoute: typeof LocalRouteWithChildren;
  LoginRoute: typeof LoginRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/login": {
      id: "/login";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_local": {
      id: "/_local";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof LocalRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_authenticated": {
      id: "/_authenticated";
      path: "";
      fullPath: "/";
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_local/projects": {
      id: "/_local/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof LocalProjectsRouteImport;
      parentRoute: typeof LocalRoute;
    };
    "/_authenticated/dashboard": {
      id: "/_authenticated/dashboard";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/$teamSlug": {
      id: "/_authenticated/$teamSlug";
      path: "/$teamSlug";
      fullPath: "/$teamSlug";
      preLoaderRoute: typeof AuthenticatedTeamSlugRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_local/projects/": {
      id: "/_local/projects/";
      path: "/";
      fullPath: "/projects/";
      preLoaderRoute: typeof LocalProjectsIndexRouteImport;
      parentRoute: typeof LocalProjectsRoute;
    };
    "/_authenticated/$teamSlug/": {
      id: "/_authenticated/$teamSlug/";
      path: "/";
      fullPath: "/$teamSlug/";
      preLoaderRoute: typeof AuthenticatedTeamSlugIndexRouteImport;
      parentRoute: typeof AuthenticatedTeamSlugRoute;
    };
    "/_local/projects/$projectSlug": {
      id: "/_local/projects/$projectSlug";
      path: "/$projectSlug";
      fullPath: "/projects/$projectSlug";
      preLoaderRoute: typeof LocalProjectsProjectSlugRouteImport;
      parentRoute: typeof LocalProjectsRoute;
    };
    "/_authenticated/settings/api-keys": {
      id: "/_authenticated/settings/api-keys";
      path: "/settings/api-keys";
      fullPath: "/settings/api-keys";
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/runs/$runId": {
      id: "/_authenticated/runs/$runId";
      path: "/runs/$runId";
      fullPath: "/runs/$runId";
      preLoaderRoute: typeof AuthenticatedRunsRunIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    "/_authenticated/$teamSlug/$appSlug": {
      id: "/_authenticated/$teamSlug/$appSlug";
      path: "/$appSlug";
      fullPath: "/$teamSlug/$appSlug";
      preLoaderRoute: typeof AuthenticatedTeamSlugAppSlugRouteImport;
      parentRoute: typeof AuthenticatedTeamSlugRoute;
    };
    "/_authenticated/$teamSlug/$appSlug/": {
      id: "/_authenticated/$teamSlug/$appSlug/";
      path: "/";
      fullPath: "/$teamSlug/$appSlug/";
      preLoaderRoute: typeof AuthenticatedTeamSlugAppSlugIndexRouteImport;
      parentRoute: typeof AuthenticatedTeamSlugAppSlugRoute;
    };
    "/_authenticated/$teamSlug/$appSlug/settings": {
      id: "/_authenticated/$teamSlug/$appSlug/settings";
      path: "/settings";
      fullPath: "/$teamSlug/$appSlug/settings";
      preLoaderRoute: typeof AuthenticatedTeamSlugAppSlugSettingsRouteImport;
      parentRoute: typeof AuthenticatedTeamSlugAppSlugRoute;
    };
  }
}

interface AuthenticatedTeamSlugAppSlugRouteChildren {
  AuthenticatedTeamSlugAppSlugSettingsRoute: typeof AuthenticatedTeamSlugAppSlugSettingsRoute;
  AuthenticatedTeamSlugAppSlugIndexRoute: typeof AuthenticatedTeamSlugAppSlugIndexRoute;
}

const AuthenticatedTeamSlugAppSlugRouteChildren: AuthenticatedTeamSlugAppSlugRouteChildren =
  {
    AuthenticatedTeamSlugAppSlugSettingsRoute:
      AuthenticatedTeamSlugAppSlugSettingsRoute,
    AuthenticatedTeamSlugAppSlugIndexRoute:
      AuthenticatedTeamSlugAppSlugIndexRoute,
  };

const AuthenticatedTeamSlugAppSlugRouteWithChildren =
  AuthenticatedTeamSlugAppSlugRoute._addFileChildren(
    AuthenticatedTeamSlugAppSlugRouteChildren,
  );

interface AuthenticatedTeamSlugRouteChildren {
  AuthenticatedTeamSlugAppSlugRoute: typeof AuthenticatedTeamSlugAppSlugRouteWithChildren;
  AuthenticatedTeamSlugIndexRoute: typeof AuthenticatedTeamSlugIndexRoute;
}

const AuthenticatedTeamSlugRouteChildren: AuthenticatedTeamSlugRouteChildren = {
  AuthenticatedTeamSlugAppSlugRoute:
    AuthenticatedTeamSlugAppSlugRouteWithChildren,
  AuthenticatedTeamSlugIndexRoute: AuthenticatedTeamSlugIndexRoute,
};

const AuthenticatedTeamSlugRouteWithChildren =
  AuthenticatedTeamSlugRoute._addFileChildren(
    AuthenticatedTeamSlugRouteChildren,
  );

interface AuthenticatedRouteChildren {
  AuthenticatedTeamSlugRoute: typeof AuthenticatedTeamSlugRouteWithChildren;
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute;
  AuthenticatedRunsRunIdRoute: typeof AuthenticatedRunsRunIdRoute;
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTeamSlugRoute: AuthenticatedTeamSlugRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRunsRunIdRoute: AuthenticatedRunsRunIdRoute,
  AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

interface LocalProjectsRouteChildren {
  LocalProjectsProjectSlugRoute: typeof LocalProjectsProjectSlugRoute;
  LocalProjectsIndexRoute: typeof LocalProjectsIndexRoute;
}

const LocalProjectsRouteChildren: LocalProjectsRouteChildren = {
  LocalProjectsProjectSlugRoute: LocalProjectsProjectSlugRoute,
  LocalProjectsIndexRoute: LocalProjectsIndexRoute,
};

const LocalProjectsRouteWithChildren = LocalProjectsRoute._addFileChildren(
  LocalProjectsRouteChildren,
);

interface LocalRouteChildren {
  LocalProjectsRoute: typeof LocalProjectsRouteWithChildren;
}

const LocalRouteChildren: LocalRouteChildren = {
  LocalProjectsRoute: LocalProjectsRouteWithChildren,
};

const LocalRouteWithChildren = LocalRoute._addFileChildren(LocalRouteChildren);

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LocalRoute: LocalRouteWithChildren,
  LoginRoute: LoginRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
